---
project: myApp
environment: unknown

vpcs:
  - name: myVPC
    subnet: 10.0.0.0/16

networks:
  - name: net-1
    vpc: myVPC
    public: true
    subnet: 10.1.0.0/24

instances:
  - name: node-1
    type: t2.micro
    image: ami-6666f915
    network: net-1
